canonical/synapse-operator

lib/charms/observability_libs/v0/juju_topology.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, metadata.yaml, src/charm.py, src/constants.py, src/observability.py, src/pebble.py, src/synapse/__init__.py, src/synapse/workload.py, tests/integration/conftest.py, tests/integration/test_charm.py, tests/unit/conftest.py, tests/unit/test_synapse_workload.py
Add Prometheus integration.
The configuration generated by migrate-config does not enable metrics so this PR adds the integration and also change the configuration to enable the metrics endpoint.
=> Add COS - Prometheus integration

requirements.txt
The ops-lib-pgsql is not needed anymore, as the legacy db relation has been removed
=> Remove ops pg lib and pin dependencies

tox.ini
This is needed as Observability have added a new library `cosl` for their code listed in libraries in PYDEPS, so we need to have this dependency in our tests as well. This is for unit tests and we might need it for integration as well.
=> fix(libs): Add cosl library as unit test requirement

lib/charms/data_platform_libs/v0/data_interfaces.py, lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/nginx_ingress_integrator/v0/nginx_route.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py
This PR updates the charm libs and should solve the issue with Grafana dashboards not appearing as described in https://github.com/canonical/grafana-k8s-operator/issues/245 and fixed in https://github.com/canonical/grafana-k8s-operator/pull/247
=> chore(libs): Update charm libs

src/synapse/workload.py, tests/unit/test_synapse_workload.py
The rock adds attributesmap to /usr/loca.
This PRs fixes the configuration and unit test according to the ROCK.
=> Fix attributemap directory

synapse_rock/attributemaps/login_ubuntu.py
This change how Synapse maps the SAMLResponse from login.ubuntu to its user management.
Currently, the field being used (fullname) is not the best option.
=> Change attributemaps

config.yaml, src/synapse/workload.py, tests/integration/conftest.py, tests/unit/test_synapse_workload.py
The entity_id provided by SAML integrator charm is being wrongly used as SP entity_id instead of IDP entity_id. This PR fixes it by setting entity_id to public_baseurl if set or https://server_name.
This way the charm can integrate with the SAML integrator as expected.
N/A
N/A
N/A
=> Fix SAML entity_id usage

synapse_rock/rockcraft.yaml
While setting Synapse environment, I noticed that one file was missing. At first I thought it would be some different version of the image but for my surprise, the rock was build successfully even trying to dump a non-existing file. This PR fixes it by adding the right name to dump.
Work as expected while mapping attributes.
=> Fix rock to dump the right file

src-docs/charm_state.py.md, src/charm_state.py, src/synapse/workload.py
Configure proxy-related environmental variables automatically according to the Juju model settings.
This is needed to make Federation (as well any request done by the Synapse) work.
=> Add proxy environment variables

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement_proposal.yml, .github/ISSUE_TEMPLATE/matrix_bug_report.yml, .github/ISSUE_TEMPLATE/matrix_enhancement.yml
Author: Philipp Kewisch
This is a copy from https://github.com/canonical/synapse-operator/pull/69 while we work on a solution to allow external contributors push packages.
Add new issue templates.
=> Workaround 1 - New issue templates for chat.ubuntu.com

src/mjolnir.py
As requested in issue #81 , this PR changes Mjolnir user to "moderator".
To take into consideration: the user created by previous versions ("mjolnir") should be manually deleted.
Make username more approachable.
N/A
N/A
N/A
=> Change Mjolnir username

actions.yaml, docs/tutorial/getting-started.md, src/charm.py, tests/integration/test_charm.py, tests/unit/test_anonymize_user_action.py
Add an action to deactivate/anonymize users.
GDPR compliance
N/A
N/A
N/A
Screenshot before and after anonymization:
=> Add anonymize user action

.woke.yaml, config.yaml, src-docs/charm_state.py.md, src-docs/pebble.py.md, src/charm_state.py, src/pebble.py, src/synapse/__init__.py, src/synapse/workload.py, tests/unit/test_charm.py, tests/unit/test_synapse_workload.py
While working with federation, one might want to restrict the servers to federate. This configuration allows that.
Reference: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#federation_domain_whitelist
Restrict servers to federate with.
N/A
N/A
N/A
=> Add federation_domain_whitelist configuration

src-docs/charm.py.md, src/charm.py, src/database_observer.py, src/mjolnir.py, src/saml_observer.py, src/synapse/workload.py, tests/integration/conftest.py, tests/unit/test_charm.py, tox.ini
If for any reason the Synapse NGINX pebble check fails, the container is restarted, a pebble ready event emitted but since there is no handler for it, the pebble plan is not re-created. This PR solves this by adding a handler to this event.
Not related but since is a small change this PR also add a strip to each item of federation domain whitelist as suggested [here](https://github.com/canonical/synapse-operator/pull/94).
Guarantee that Synapse NGINX pebble layer is always planned.
Add _on_synapse_nginx_pebble_ready
N/A
N/A
=> Add Synapse NGINX pebble ready event handler

src-docs/charm.py.md, synapse_rock/rockcraft.yaml
This PR changes the ROCK image to install Synapse version 1.96.1. Also, since SBOM is not available for ROCKs yet, it creates a file rust-version to make it possible check the Rust version installed at the time of the image creation.
Upgrade Synapse.
N/A
N/A
N/A
=> Upgrade Synapse (already published)

config.yaml, src-docs/charm_state.py.md, src-docs/pebble.py.md, src/charm_state.py, src/pebble.py, src/synapse/__init__.py, src/synapse/workload.py, tests/unit/test_charm.py, tests/unit/test_mjolnir.py, tests/unit/test_synapse_workload.py
While working with federation, one might want toallow public rooms over federation. This configuration allows that.
Reference: https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html#allow_public_rooms_over_federation
Change allow_public_rooms_over_federation configuration.
=> Add allow_public_rooms_over_federation configuration

.github/workflows/integration_test.yaml, tox.ini
Use `edge` self-hosted runner for integration test
- Reduce load on GitHub-provided runner on the organisation.
- Test out the edge revision of github-runner charm on this repo.
=> Use self-hosted runner for integration test

nginx_rock/etc/nginx.conf
Nginx container is logging lines like the following one:
`2023-11-27T13:51:05.555Z [synapse-nginx] 2023/11/27 13:51:05 [error] 34#34: *736 no live upstreams while connecting to upstream`...
The error log can be removed changing `proxy_pass` directive from `localhost` to `127.0.0.1` (see [here](https://stackoverflow.com/questions/49767001/how-to-solve-nginx-no-live-upstreams-while-connecting-to-upstream-client) for more information)
=> Update nginx proxy_pass from localhost to 127.0.0.1

src-docs/backup.py.md, src/backup.py, src/backup_observer.py, tests/integration/conftest.py, tests/unit/conftest.py, tests/unit/test_backup.py, tests/unit/test_backup_observer.py
As a first step before the main [PR](https://github.com/canonical/synapse-operator/pull/171) for the backup action, the S3 interface is changed for the backup.
The interface for s3 now is just the function `can_use_bucket`. Other functions will be needed, like `list_objects`/`list_backups`, `delete_object`/`delete_backup`, and they will all use the same boto s3 client. A class is used to provide a simpler interface and will share the low level boto3 client. The other methods will be created in next PRs.
The low level client with S3 has been changed to use s3 client interface, as sometimes in the project (in the tests) the client interface was used and other times it was the resource interface.
Other some minor improvements have been made (use of the host/path property in S3 and putting …
=> Refactor S3 Client for Backup

pyproject.toml, tests/integration/test_charm.py
Adds custom pytest markers to the `pyproject.toml`.
pytest complains on tests that the markers are not defined.
n/a
Added an additional `s3` marker in the integration tests if you want to skip the s3 localstack tests.
n/a
- [x ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)
=> chore(pytest): Add custom markers

actions.yaml, src-docs/backup.py.md, src-docs/backup_observer.py.md, src/backup.py, src/backup_observer.py, tests/integration/test_charm.py, tests/unit/test_backup.py, tests/unit/test_backup_observer.py
Applicable spec: ISD095
This PR creates the action `list-backups` action in Synapse. 
The backups created with the action `create-backup` will be created in a specific prefix in the S3 repository, and they will be read and listed by this action, with some extra information. Its output will be like this:
```
juju run synapse/leader list-backups
Running operation 51 with 1 task
- task 52 on unit-synapse-0
Waiting for task 52...
backups:
backup-20240206100503602202:
last-modified: 2024-02-06 10:05:05.945000+00:00
size: "40699"
backup-20240206152530632850:
last-modified: 2024-02-06 15:25:33.826000+00:00
size: "40698"
backup-20240206152707269036:
last-modified: 2024-02-06 15:27:09.728000+00:00
size: "40699"
backup-20240207074717616279:
last-modified: 2024-02-07 07:47:18.803000+00:00
size: …
```
=> List backups action

.github/workflows/promote_charm.yaml
Documentation is not being published when the charm is promoted. It should be published, as now it is outdated.
=> Publish doc when promoting the charm

synapse_rock/rockcraft.yaml
- Update synapse to 1.101.0
- Update poetry to 1.7.1
- Pin version for the rust toolchain to 1.76.0
=> Update synapse/poetry versions, pin version for the rust toolchain

.github/workflows/integration_test.yaml, docs/reference/integrations.md, src-docs/charm.py.md, src-docs/charm_state.py.md, src-docs/charm_types.py.md, src-docs/pebble.py.md, src-docs/redis_observer.py.md, src/charm.py, src/charm_state.py, src/charm_types.py, src/pebble.py, src/redis_observer.py, src/synapse/__init__.py, src/synapse/workload.py, tests/integration/test_redis.py, tests/unit/conftest.py, tests/unit/test_admin_access_token.py, tests/unit/test_charm.py, tests/unit/test_synapse_api.py, tests/unit/test_synapse_workload.py
After integrating with Redis, the charm will change the Synapse configuration with host and port information from relation data.
Redis integration is required by horizontal scaling configuration.
redis_relation_updated changes Synapse configuration via pebble_service.
N/A
N/A
=> Add Redis configuration when integrating with Redis charm

src/prometheus_alert_rules/synapse.rule
Update alert memory to 3GB, as the previous limit, 1GB is insufficient for a federated server where users use big rooms.
=> Increase memory alert to 3GB

src-docs/charm.py.md, src/charm.py, tests/unit/test_charm_scaling.py
Note: Integration test will be added in further story/PR.
Synapse Horizontal scaling design requires that for every change in the number of worker (up or down), they all should be restarted. This PR does that by observing events relation-changed and relation-departed, for each of them, if the unit is not the main unit  then will be restarted.
Restart workers as required by horizontal scaling design.
Relation departed event.
Documentation will be added in horizontal scaling is in place.
=> Restart worker for relation departed and relation changed

src-docs/database_observer.py.md, src-docs/pebble.py.md, src/grafana_dashboards/synapse_statistics.json
This PR adds a Grafana dashboard for metrics collected by the [Synapse Stats Exporter](https://github.com/canonical/synapse_stats_exporter).
Offer metrics visualization. So far, only two: number of rooms and number of users.
No need of updating charmhub documentation.
=> Add Synapse Statistics grafana dashboard

requirements.txt, src-docs/backup_observer.py.md, src-docs/charm_state.py.md, src-docs/database_client.py.md, src-docs/pebble.py.md, src/database_client.py, src/pebble.py
Currently, most events trigger a restart even if the configuration has not changed. This will prevent that by checking the configuration before the restart.
Prevent constant restarts like we saw in Production handling database relation changed in second unit.
Config change event and integration related. Synapse will only restart if the generated configuration is different from the existing one in the workload.
No need to update CH doc.
=> Verify if configuration has changed before restarting Synapse

requirements.txt, src/synapse/workload.py
Points to FQDN so that image links work (with the previous SYNAPSE_URL you would get a `localhost` reference that is broken).
No more broken links.
`src/synapse/workload.py`: in `_get_irc_bridge_config` the `url` now takes the server name from the (charm state) synapse config.
n/a
- [x ] The PR is tagged with appropriate label (`urgent`, `trivial`, …
=> fix(irc): Point to FQDN

src/observability.py
One char PR, my favorite - using `log_files` is not valid, if you look (closely) at the docs, it says `log-files`. It fails very silently, though still an user error. This PR fixes that.
Make logs work.
n/a
`src/observability.py` uses the correct key for logs
n/a
- [x ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)
=> fix(loki): Use valid key for log files

src-docs/mjolnir.py.md, src/charm.py, src/mjolnir.py
Scenario: leader unit is the main and unexpectedly fails. The relation departed event is not emitted.
This PRs changes the leader_elected event to configure the current leader as the main unit so this will be done in two cases:
- when the charm is deployed
- when the current leader fails and another one is elected
Resiliency.
There is no charmhub documentation regarding horizontal scaling yet (to be done in different story)
=> Fix _on_leader_elected and Mjolnir in case of current leader failure

src/grafana_dashboards/synapse.json, src/prometheus_alert_rules/synapse.rule
This PR:
- Fix CPU usage and Memory panels
- Add panel Synapse Units by Juju Model
- Add SynapseUnitsChanged and SynapseHighEventRate alerts
Improve monitoring considering horizontal scaling.
No charmhub doc for horizontal scaling yet.
=> Fix Grafana panels and add Prometheus alerts

.github/workflows/publish_charm.yaml
Run publish on push to track/*
=> Enable tracks for version control

src/grafana_dashboards/synapse_statistics.json
Currently the dashboard looks like this:
This PR will change to show users and rooms in a time-series like this:
=> feat: replace Synapse Statistics grafana dashboard panels

charmcraft.yaml, requirements.txt
Charmcraft pack throws the following error:
```
2024-08-01 14:12:59.657 :: 2024-08-01 14:12:57.493 ::    ::   × Building wheel for rpds-py (pyproject.toml) did not run successfully.
2024-08-01 14:12:59.657 :: 2024-08-01 14:12:57.493 ::    ::   │ exit code: 1
2024-08-01 14:12:59.657 :: 2024-08-01 14:12:57.493 ::    ::   ╰─> [13 lines of output]
2024-08-01 14:12:59.657 :: 2024-08-01 14:12:57.494 ::    ::       Running `maturin pep517 build-wheel -i /root/parts/charm/build/staging-venv/bin/python3 --compatibility off`
2024-08-01 14:12:59.657 :: 2024-08-01 14:12:57.494 ::    ::       📦 Including license file "/tmp/pip-install-1i7phoq9/rpds-py_e2f441b374f04c92932669e3b4817ee9/LICENSE"
2024-08-01 14:12:59.657 :: 2024-08-01 14:12:57.494 ::    ::       🔗 Found pyo3 bindings
2024-08-01 …
```
=> fix: add rustup snap

src/synapse/api.py, tests/unit/test_synapse_api.py
The call to override_ratelimit already exists but for some misunderstanding, it was called with DELETE instead of POST.
This PR fixes the call so an override_rate limit is added to Mjolnir user.
References: 
https://github.com/matrix-org/synapse/issues/6286
https://element-hq.github.io/synapse/latest/admin_api/user_admin_api.html#set-ratelimit
=> fix: fix call to override_ratelimit

src/grafana_dashboards/synapse.json, src/observability.py, tests/unit/test_observability.py, tox.ini
…nds_total duplication
After creating a theory connecting multiple cores to the unusually high values for process_cpu_seconds_total, it turns out the real cause was two Prometheus targets with the same metrics and labels.
This PR fixes that by splitting the targets into two jobs and revert changes in Grafana dashboard to show CPU usage as %.
Screenshot
=> fix: split prometheus targets into two jobs

config.yaml, src-docs/charm_state.py.md, src-docs/pebble.py.md, src/charm_state.py, src/pebble.py, src/synapse/__init__.py, src/synapse/workload_configuration.py, tests/unit/test_synapse_workload.py, tox.ini
This PR adds a new configuration limit_remote_rooms_complexity that prevents a user from joining rooms with a complexity bigger than the one set.
Prevent performance issues by limiting remote complex rooms.
=> feat: add limit_remote_rooms_complexity configuration

.github/workflows/integration_test.yaml, metadata.yaml, src-docs/mjolnir.py.md, src/mjolnir.py, tests/unit/test_mjolnir.py
Mjolnir should run only in the main unit but when it changes, it keeps running in the previous one.
This PR guarantees that Mjolnir is not configured and is stopped in the worker units if enabled.
Collec status.
=> fix: stop Mjolnir if is running in a worker unit

config.yaml, src-docs/charm_state.py.md, src-docs/pebble.py.md, src/charm_state.py, src/pebble.py, src/synapse/__init__.py, src/synapse/workload_configuration.py, tests/unit/test_synapse_workload.py
Add the possibility for a charm operator to enable the `block_non_admin_invite` option on Synapse
See documentation: https://element-hq.github.io/synapse/latest/usage/configuration/config_documentation.html?highlight=block_non_ad#block_non_admin_invites
Following a SPAM attack on our Ubuntu community matrix server where the spammer is creating rooms in other servers than our homeserver and sending invites to these rooms containing NFSW content, we decided to add this option in order to enable it in case of "emergency" situation.
N/A
Added a charm config option, reflected in CharmState.
Added a Synapse Workload method to add this configuration option into Synapse homeserver.yaml file.
N/A
=> Add support for block non admin invites

src/charm.py
Remove deprecated ops.main.main
https://ops.readthedocs.io/en/latest/#ops-main-entry-point
Use new one ops.main
=> fix: replace deprecated ops.main.main for ops.main

src/grafana_dashboards/synapse.json
This PR changes Prometheus query for counting the number of active units for each model.
The previous one was counting series with the job related to the synapse-stats-exporter, resulting in a number different than the expected.
=> fix: fix synapse units panel
