- metadata.yaml
- synapse_rock/rockcraft.yaml
- tests/conftest.py
Add Synapse rockfile based on https://github.com/matrix-org/synapse/blob/develop/docker/Dockerfile
obs.: Branch with wrong name, the right one would be ISD-782
Bash package is needed otherwise SQLite throws an error "sqlite3.OperationalError: disk I/O error"
> chore(ISD-782): Add Synapse rock

- .gitignore
- .licenserc.yaml
- lib/charms/traefik_k8s/v1/ingress.py
- metadata.yaml
- src/charm.py
- src/constants.py
- tests/integration/conftest.py
- tests/integration/test_charm.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
This PR adds Traefik integration to Synapse charm. Unit and Integration tests included.
> feat(ISD-844): Add Traefik integration

- README.md
> chore(ISD-783): Add badges

- requirements.txt
- src/charm.py
Fix #11 
In case of event pebble ready, will configure and replan.
> fix(ISD-893): Handle pebble ready event

- metadata.yaml
* Add valid maintainers link
* Add discourse post for the docs
> Fix metadata contents

- .github/PULL_REQUEST_TEMPLATE.md
- .github/pull_request_template.md
This PR adds a template for future PRs.
> Add PULL_REQUEST_TEMPLATE.md

- src/synapse/api.py
Fix linting errors
Fixes some linting errors
N/A
N/A
N/A
N/A
> Fix linting

- renovate.json
- synapse_rock/rockcraft.yaml
Enable digest pinning for rocks and updates via renovate.
Automated image build frequency.
n/a
n/a
n/a
- [ x] The [charm style guide](https://juju.is/docs/sdk/styleguide) was applied
- [ x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [ x] The changes are compliant with [ISD054 - Manging Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [ x] The documentation is generated using `src-docs`
- [ x] The documentation for charmhub is updated.
- [ x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)
> feat(digests): Enable digest pinning

- src/prometheus_alert_rules/synape.rule
This PR adds Prometheus alert rules to improve Synapse monitoring.
Prevent downtimes.
N/A
N/A
N/A
> Add Prometheus alerts

- synapse_rock/rockcraft.yaml
micro PR - adds the irc bridge snap, configuring it in the charm is part of a subsequent PR
needed for IRC bridging
n/a
n/a
n/a
- [x ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)
> feat(irc): Add irc bridge

- src/pebble.py
Fix usage of a synapse constant.
> Minor fix to restart_synapse()

- metadata.yaml
- src/charm.py
- src/charm_state.py
- src/database_observer.py
- src/irc_bridge.py
- src/synapse/workload.py
- templates/irc_bridge_production.yaml
- tests/integration/test_charm.py
- tests/unit/test_irc_bridge.py
- tests/unit/test_synapse_api.py
- tests/unit/test_synapse_workload.py
Adds a database for the IRC bridge.
The IRC bridge needs a database.
New database observer.
Changes to the database observer to allow for multiple dbs.
n/a
- [x ] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)
> feat(irc-bridge): Add irc database

- .github/workflows/integration_test.yaml
Circumvent runners, they slow and botch our tests.
Needs to be merging stuff.
n/a
n/a
n/a
- [ x] The [contributing guide](https://github.com/canonical/is-charms-contributing-guide) was applied
- [ x] The changes are compliant with [ISD054 - Manging Charm Complexity](https://discourse.charmhub.io/t/specification-isd014-managing-charm-complexity/11619)
- [ x] The documentation for charmhub is updated.
- [ x] The PR is tagged with appropriate label (`urgent`, `trivial`, `complex`)
> fix(tests): Bye runner bye

- templates/mjolnir_production.yaml
- tests/integration/conftest.py
This way NGINX can reach Mjolnir API allowing users to send abuse reports.
localhost was not being resolved in a proxy_pass directive
> Change Mjolnir web address to fix abuse reports

- docs/index.md
Add missing how-to index to documentation for backup and restore.
> Add missing how-to index to documentation

- src-docs/charm.py.md
- src/charm.py
- synapse_rock/rockcraft.yaml
This PR change the rock by building Synapse Stats Exporter together with Synapse.
Synapse Stats Exporter is needed to collect statistics from Synapse.
Documentation will be updated once the Synapse Stats Exporter dashboard is in place.
> Build Synapse Stats Exporter in Synapse rock

- README.md
- docs/how-to/contribute.md
- docs/index.md
- docs/tutorial/getting-started.md
Update CharmHub chat link to Matrix.
Also other minor doc improvements.
The previous link points to the archived chat channel.
> Update docs. CharmHub chat link to Matrix and other minor issues.

- docs/reference/external-access.md
Add external access reference.
Update documentation with external access reference.
> Add external access reference

- tox.ini
N/A
Fix codespell config by ignoring the problematic word needed by the dashboards
N/A
N/A
N/A
N/A
> Fix codespell config

- requirements.txt
> Test new workflow

- docs/how-to/horizontally-scale.md
This PR adds a how to about scaling Synapse up.
Horizontal scaling is in place but we don't have a documentation about it yet.
> docs: add horizontally scale how-to

- config.yaml
- src-docs/charm_state.py.md
- src-docs/pebble.py.md
- src/charm_state.py
- src/pebble.py
- src/synapse/__init__.py
- src/synapse/workload_configuration.py
- synapse_rock/rockcraft.yaml
- tests/unit/test_synapse_workload.py
This PR adds the synapse-invite-checker module.
https://git.buechner.me/nbuechner/synapse-invite-checker/src/branch/main
Moderate invites.
> feat: add synapse-invite-checker

- src/charm_state.py
- tests/integration/test_charm.py
Fix regex for room ids.
Replace regex.
> fix: replace regex for room ids

- synapse_rock/rockcraft.yaml
Bump Synapse version.
Update workload.
> feat: bump Synapse to 1.115.0

- src/synapse/workload_configuration.py
- synapse_rock/rockcraft.yaml
- tests/unit/test_synapse_workload.py
Update module and fix configuration field.
Enable invite checker module as expected.
> fix: update module and fix configuration

- src-docs/user.py.md
- tests/integration/conftest.py
- tox.ini
This PR removes fixtures that are not being used.
Refactor/"cleaning"
> chore(refactor): remove fixtures
